# 전반적인 API 명세입니다 참고하세용

# 로그인 기능 : /api/auth/login
# 회원가입 기능 : /api/auth/signup
# 내 정보 조회 기능 : /api/auth/me

# ctrl + f로 빠르게 찾아가세용

openapi: 3.0.3
info:
  title: onDongne API
  version: 0.1.0
  description: |
    onDongne 인증 API 최소 명세 (문서용)
    - 회원가입, 로그인, 내 정보 조회
servers:
  - url: http://localhost:4000
    description: 로컬 서버

paths:
  /api/auth/signup:
    post:
      summary: 회원가입
      description: 이메일/비밀번호/이름을 받아 새 사용자를 생성한다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthSignupRequest'
            examples:
              기본:
                value:
                  email: test@test.com
                  password: mypw
                  name: 천호준
      responses:
        '201':
          description: 가입 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: 잘못된 요청(필수 값 누락 등)
        '409':
          description: 중복 이메일

  /api/auth/login:
    post:
      summary: 로그인
      description: 이메일/비밀번호로 로그인하고 액세스 토큰을 발급한다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthLoginRequest'
            examples:
              기본:
                value:
                  email: test@test.com
                  password: mypw
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: 잘못된 요청(필수 값 누락 등)
        '401':
          description: 인증 실패(이메일/비밀번호 불일치)

  /api/auth/me:
    get:
      summary: 내 정보 조회
      description: Bearer 토큰으로 인증된 사용자 정보를 반환한다.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 사용자 정보
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/User'
        '401':
          description: 토큰 누락/유효하지 않음
        '404':
          description: 사용자를 찾을 수 없음

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AuthSignupRequest:
      type: object
      required: [email, password, name]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1

    AuthLoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 1

    User:
      type: object
      properties:
        id:
          type: string
          example: '1'
        email:
          type: string
          example: test@test.com
        name:
          type: string
          example: 홍길동
        createdAt:
          type: string
          format: date-time

    AuthResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            user:
              $ref: '#/components/schemas/User'
            accessToken:
              type: string
              example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...


