// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsFq8gucRBW_2xdUgYuUZ6aHBwddSs7Iw',
    appId: '1:58574278323:web:0bbef9d893d2226a212ac6',
    messagingSenderId: '58574278323',
    projectId: 'ondongne-e494a',
    authDomain: 'ondongne-e494a.firebaseapp.com',
    storageBucket: 'ondongne-e494a.firebasestorage.app',
    measurementId: 'G-YVTH4ENKTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJuBINCMYV8dpAZQYz2FuAJRP682tFpJA',
    appId: '1:58574278323:android:8ed9a28a2c30351b212ac6',
    messagingSenderId: '58574278323',
    projectId: 'ondongne-e494a',
    storageBucket: 'ondongne-e494a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7CizBYGVZem4nIxLOzBTjHP6bSKbAmxs',
    appId: '1:58574278323:ios:39dcba8029218eaa212ac6',
    messagingSenderId: '58574278323',
    projectId: 'ondongne-e494a',
    storageBucket: 'ondongne-e494a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7CizBYGVZem4nIxLOzBTjHP6bSKbAmxs',
    appId: '1:58574278323:ios:39dcba8029218eaa212ac6',
    messagingSenderId: '58574278323',
    projectId: 'ondongne-e494a',
    storageBucket: 'ondongne-e494a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsFq8gucRBW_2xdUgYuUZ6aHBwddSs7Iw',
    appId: '1:58574278323:web:863a6511928a0903212ac6',
    messagingSenderId: '58574278323',
    projectId: 'ondongne-e494a',
    authDomain: 'ondongne-e494a.firebaseapp.com',
    storageBucket: 'ondongne-e494a.firebasestorage.app',
    measurementId: 'G-K79F5NGE65',
  );
}
